### ISSUE TITLE
Unresolved dependency

### ISSUE THREAD

**Issue by aletundo** [teamdigitale/daf-event-producers#4]
I cannot compile the code due to an unresolved dependency:

`it.gov.daf#daf-iot-ingestion-manager-common_2.11;1.0-SNAPSHOT: not found`

Is it resolved from the local repository?

I added a `.travis.yml` within my fork, so you can see the build log [here](https://travis-ci.org/aletundo/daf-event-producers/builds/306354151) :)

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
